packages:
  - apps/*
  - apps/runtime-go/cmd/awsm/frontend
  - packages/*

overrides:
  "@huggingface/transformers@4.2.0>onnxruntime-node": "-"
  "@huggingface/transformers@4.2.0>sharp": "-"

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  geckodriver: true
  protobufjs: false
  spawn-sync: true
