development:
  adapter: redis
  url: <%= Coordination::EphemeralCoordination.url %>
  channel_prefix: <%= Coordination::EphemeralCoordination.channel_prefix %>

test:
  adapter: <%= ENV.fetch("AWSM_CABLE_ADAPTER", "test") %>
  url: <%= Coordination::EphemeralCoordination.url %>
  channel_prefix: <%= Coordination::EphemeralCoordination.channel_prefix %>

production:
  adapter: redis
  url: <%= Coordination::EphemeralCoordination.url %>
  channel_prefix: <%= Coordination::EphemeralCoordination.channel_prefix %>
