# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  dispatch_account_deletions:
    class: DispatchAccountDeletionsJob
    queue: default
    schedule: every hour
  expire_opaque_uploads:
    class: ExpireOpaqueUploadsJob
    queue: default
    schedule: every hour at minute 5
  dispatch_hosted_replica_reaping_jobs:
    class: DispatchHostedReplicaReapingJobsJob
    queue: default
    schedule: every hour at minute 10
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
